// Default Paramaters
def default_not_jenkins_addr = "https://not-jenkins2.thehempathy.com"
def default_not_jenkins_secret = "not_jenkins_token"


// Internal variable for pipeline
def invalidParam = false
def autoCancelled = false

pipeline {
    agent any

    parameters {
        //string(name: 'dockerNamespace', description: 'Docker Name Space')
//        string(name: 'dockerNamespace', defaultValue: 'thehempathy', description: 'Docker Name Space')


        //string(name: 'dockerImageName', description: 'The last extension of a docker image name')
//        string(name: 'dockerImageName', description: 'The last extension of a docker image name')
        string(name: 'dockerImage', description: 'The last extension of a docker image name')

        //string(name: 'dockerTag', description: 'The Docker Tag to be deploy')
        string(name: 'dockerTag', defaultValue: 'latest', description: 'The last extension of a docker image name')

        //string(name: 'dockerStackName', description: 'Docker Stack Name to deploy to')
        string(name: 'dockerStackName', defaultValue: 'thehempathy', description: 'Docker Stack Name to deploy to')
        //string(name: 'dockerEnv', description: 'The environment to deploy to.')
        string(name: 'dockerEnv', defaultValue: 'dev', description: 'The last extension of a docker image name')
        //string(name: 'dockerServiceName', description: 'Docker Service Name to deploy to')
        string(name: 'dockerServiceName', defaultValue: 'backend_express', description: 'Docker Service Name to deploy to')

        string(name: 'notJenkinsAddr', defaultValue: "${default_not_jenkins_addr}", description: 'Not Jenkins Base Url')
        string(name: 'notJenkinsSecret', defaultValue: "${default_not_jenkins_secret}", description: 'Not Jenkins secret')

    }


    environment {


        DOCKER_IMAGE = "${params.dockerImage}"

        DOCKER_VERSION = "${params.dockerTag}"

        NOT_JENKINS_URL = "${params.notJenkinsAddr}/${params.dockerStackName}-${params.dockerEnv}/${params.dockerServiceName}"

        NOT_JENKINS_SECRET = credentials("${params.notJenkinsSecret}")

    }

    stages {
        stage ('Validate Parameters') {

            steps {
                script {
                    params.each { key, value ->
                        if ( !value || value == "" ) {
                            echo "Param ${key} was not set"
                            invalidParam = true
                        }
                    }
             
                    if ( invalidParam ) {
                        echo "Invalid parameters detected. Aborting pipeline..."
                        autoCancelled = true
                        currentBuild.result = 'FAILURE'

                    }
                }
            }

        }

        stage('Deploy') {
            when {
                expression {
                    return !autoCancelled
                }
            }
            steps {
                echo 'Deploying ...'

                script {
                    sh 'chmod +x ./deploy/scripts/deploy.sh'
                    sh 'sudo -E ./deploy/scripts/deploy.sh'
                }
            }
        }
        stage('Test') {
            when {
                expression {
                    return !autoCancelled
                }
            }
            steps {
                echo 'Testing ...'
                echo 'Actually doing nothing.'
                //sh 'sudo -E ./jenkins/scripts/test.sh'
            }
        }
    }
}